#http://localhost/api/v1/swagger-ui/index.html
server:
  port: 80
  servlet:
    context-path: /api/v1
    encoding:
      charset: UTF-8
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/e-commerce
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop